chat_django/chat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from .views import (
    ListUsers,
    list_chats,
    messages
)


urlpatterns = [
    #url(r'^(?P<user_id>\d+)/$', ListChats.as_view(), name='detail'),
    url(r'^(?P<user_id>\d+)/$', list_chats, name="list-chats"),
    #url(r'^(?P<user_id>\d+)/new/$', messages, name='messages_new'),
    url(r'^(?P<user_id>\d+)/(?P<room_id>\d+)/$', messages, name='messages'),
    #url(r'^(?P<pk>\d+)/$', ListChats.as_view(), name='detail'),
    #url(r'^editar/(?P<pk>\d+)$', CourseUpdate.as_view(), name='edit'),
    #url(r'^borrar/(?P<pk>\d+)$', CourseDelete.as_view(), name='delete'),
    url(r'^', ListUsers.as_view(), name='list'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat_django/chat_django/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('chat.urls', namespace='chat')),
]

chat_django/chat/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User


class Room(models.Model):
    name = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User)
    last_message = models.ForeignKey('Message', blank=True, null=True, verbose_name='Last message', related_name='last_messages')

    def __str__(self):
        return self.user.username

class Message(models.Model):
    user = models.ForeignKey(User)
    room = models.ForeignKey(Room, related_name='messages')
    message = models.TextField()
    time = models.DateTimeField(default=timezone.now, db_index=True)

    def __str__(self):
        return '[%s]: %s' % (self.time, self.message)

    def room_post_save(sender, instance, created, **kwargs):
        Room.objects.get_or_create(user=instance.user_id)

    def message_post_save(sender, instance, created, **kwargs):
        Room.objects.filter(id=instance.user_id).update(last_message=instance)

chat_django/chat/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.db.models.query_utils import Q
from django.contrib.auth.models import User

from .models import Message


class MessageSendForm(forms.ModelForm):

    class Meta:
        model = Message
        exclude = ('user', 'room', 'time')

chat_django/chat/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.db.models import Q
from django.views.generic.edit import (
    CreateView,
    UpdateView
)
from django.contrib.auth.models import User

from .models import Room, Message
from .forms import MessageSendForm


class ListUsers(ListView):
    model = User
    context_object_name = 'user_list'
    queryset = User.objects.filter(is_active=True, is_superuser=False)
    template_name = 'chat/user_list.html'


def list_chats(request, user_id):
    if user_id is not None:
        user = User.objects.get(id=user_id)
        users = User.objects.filter(~Q(id=user_id), is_active=True, is_superuser=False)

        return render(request, 'chat/room_list.html',
            {'list_users': users,
            'usuario': user.id})
    else:
        return render(request, 'chat/room_list.html')


def messages(request, user_id, room_id=None):
    user = User.objects.get(id=user_id)
    form = MessageSendForm()
    if request.method == 'POST':
        form = MessageSendForm(request.POST)
        if form.is_valid():
            #import pdb; pdb.set_trace()
            room_chat = Room.objects.get(id=room_id)
            message = form.save(commit=False)
            message.message = request.POST['message']
            message.room = room_chat
            message.user = user
            message.save()

    if room_id:
        room_chat, created = Room.objects.get_or_create(user=user_id)
        #messages = Message.objects.filter(room=room_chat[0], user=)
        messages = reversed(room_chat.messages.order_by('-time')[:50])
        users = User.objects.filter(~Q(id=user_id), is_active=True, is_superuser=False)

        return render(request, 'chat/chat.html',
            {'messages': messages,
            'users': users,
            'user_chat': user.username,
            'usuario': user.id,
            'user_name': '%s %s' % (user.first_name, user.last_name),
            'form': form})
    else:
        return render(request, 'chat/room_list.html')

chat_django/chat/templates/chat/chat.html
{% extends "base.html" %}

{% block content %}
			<div class="jumbotron well">
				<h2>
                    Bienvenid@ {{ user_name }}.
				</h2>
				<p>
				    Comunicación sencilla y fácil.
				</p>
			</div>
			<div class="row">
				<div class="col-md-6">
  <form id="chatform" action="." method="post">{% csrf_token %}
    <table id="chat" class="table table-hover table-bordered">
      <tbody>
        {% for message in messages %}
          <tr>
            <td>{{ message.message }}</td>
            <td>{{ message.user.username }}</td>
            <td>{{ message.time|date:'d-m-Y H:i' }}</td>
          </tr>
        {% endfor %}
      </tbody>
      <tfoot>
      <tr>
        <td>
            <div class="col-md-8">
            <div class="input-group">
                <span class="input-group-addon">SMS</span>
                <input name="{{ form.message.name }}" id="{{ form.message.name }}" type="text" class="form-control" placeholder="Escribir...">
            </div>
            </div>
                <button type="submit" id="enviar" class="btn btn-success">Enviar</button>
        </td>
        <td align="center"> <p style="color: #419641; font-size: 20px;"> {{ user_chat }} </p></td>
      </tfoot>
    </table>
  </form>
				</div>
				<div class="col-md-6">
                    <h3 align="center">Usuarios</h3>
					<table class="table table-hover table-bordered">
						<thead>
							<tr>
								<th>
									#
								</th>
								<th>
									Nombre
                                </th>
                                <th>
									Apellido
								</th>
							</tr>
                        </thead>
						<tbody>
                            {% for user in users %}
                                {% for room in user.room_set.all %}
                                <tr class="success">
                                    <td>
                                        <a href="{% url "chat:messages" usuario room.id %}">{{ user.username }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url "chat:messages" usuario room.id %}">{{ user.first_name }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url "chat:messages" usuario room.id %}">{{ user.last_name }}</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            {% endfor %}
						</tbody>
					</table>
				</div>
			</div>
{% endblock content %}

chat_django/chat/templates/chat/room_list.html
{% extends "base.html" %}

{% block content %}
			<div class="jumbotron well">
				<h2>
					Bienvenido.
				</h2>
				<p>
				    Comunicación sencilla y fácil.
				</p>
			</div>
			<div class="row">
				<div class="col-md-6">
                    <h3 align="center">Usuarios</h3>
					<table class="table table-hover table-bordered">
						<thead>
							<tr>
								<th>
                                    Username
								</th>
								<th>
                                    Nombre
								</th>
								<th>
                                    Apellido
								</th>
							</tr>
						</thead>
						<tbody>
                            {% for user in list_users %}
                                {% for room in user.room_set.all %}
                                <tr class="success">
                                    <td>
                                        <a href="{% url "chat:messages" usuario room.id %}">{{ user.username }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url "chat:messages" usuario room.id %}">{{ user.first_name }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url "chat:messages" usuario room.id %}">{{ user.last_name }}</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            {% endfor %}
						</tbody>
					</table>
				</div>
				<div class="col-md-6">
					<table class="table table-hover table-bordered">
						<thead>
							<tr>
								<th>
									#
								</th>
								<th>
									Product
								</th>
								<th>
									Payment Taken
								</th>
								<th>
									Status
								</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>
									1
								</td>
								<td>
									TB - Monthly
								</td>
								<td>
									01/04/2012
								</td>
								<td>
									Default
								</td>
							</tr>
							<tr class="active">
								<td>
									1
								</td>
								<td>
									TB - Monthly
								</td>
								<td>
									01/04/2012
								</td>
								<td>
									Approved
								</td>
							</tr>
							<tr class="success">
								<td>
									2
								</td>
								<td>
									TB - Monthly
								</td>
								<td>
									02/04/2012
								</td>
								<td>
									Declined
								</td>
							</tr>
							<tr class="warning">
								<td>
									3
								</td>
								<td>
									TB - Monthly
								</td>
								<td>
									03/04/2012
								</td>
								<td>
									Pending
								</td>
							</tr>
							<tr class="danger">
								<td>
									4
								</td>
								<td>
									TB - Monthly
								</td>
								<td>
									04/04/2012
								</td>
								<td>
									Call in to confirm
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
{% endblock content %}

chat_django/chat/templates/chat/user_list.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <table id="chat" class="table table-hover table-bordered">
				<div class="col-md-12">
                    <h3 align="center">Lista de Usuarios Disponibles</h3>
					<table class="table table-hover table-bordered">
						<thead>
							<tr>
								<th>
									#
								</th>
								<th>
									Nombre Apellido
                                </th>
							</tr>
                        </thead>
						<tbody>
                            {% for user in user_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href=" {% url "chat:list-chats" user.id %}"> {{ user.first_name }} {{ user.last_name }}</a></td>
                            </tr>
                            {% endfor %}
						</tbody>
					</table>
				</div>
			</div>
{% endblock content %}

chat_django/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}## Chat ##{% endblock %}</title>

    <meta name="description" content="Django Chat">
    <meta name="author" content="Rodrigo Bravo">

    <link href="{% static "src/css/bootstrap.min.css" %}" rel="stylesheet" />
    <link href="{% static "src/css/bootstrap-theme.min.css" %}" rel="stylesheet" />
  </head>
  <body>
    <br>
    <div class="container">
	    <div class="row">
		    <div class="col-md-12">
                <ul class="nav nav-tabs">
                    <li>
                        <a href="{% url "chat:list" %}">Inicio</a>
                    </li>
                    <li>
                        <a href="/admin/">Admin</a>
                    </li>
                </ul>
                {% block content %}{% endblock content %}
		    </div>
	    </div>
    </div>
  </body>
</html>